language: node_js
matrix:
  include:
    - node_js: "8"
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
after_success:
  - npm run coverage
# - (send to coveralls)
# - (send to codecov)